### ISSUE TITLE
3D printed Case sketches

### ISSUE THREAD

**Issue by thorstenweber83** [ConnyCola/SolderingStation#1]
It would be really nice to also have the plans for the 3D printed enclosure!
Maybe you can ask your 3D printing friend to add them to the repo.

thanks in advance
Thorsten

**Comment by ConnyCola** [comment]
Hi Thorsten, 
I added the 3D files. I don't really know if you can work with this format but I just hope so :)

**Comment by thorstenweber83** [comment]
very nice thank you!
